name: Package & release VSCode AppImage

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta a las 12:00 AM UTC cada día
  workflow_dispatch:     # Permite la ejecución manual del workflow

permissions:
  contents: write  # Permitir escritura en el repositorio (incluyendo tags)

jobs:
  download-and-unpack:
    name: Download and Unpack VSCode
    runs-on: ubuntu-latest
    outputs:
      packaged_path: ${{ steps.save-paths.outputs.packaged_path }}
      unpacked_path: ${{ steps.save-paths.outputs.unpacked_path }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libfuse2

      - name: Download latest VSCode
        id: download
        run: |
          wget -O vscode.tar.gz "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
          echo "PACKAGED_PATH=${{ github.workspace }}/vscode.tar.gz" >> $GITHUB_ENV

      - name: Unpack VSCode
        id: unpack
        run: |
          mkdir vscode
          tar -xzvf ${{ env.PACKAGED_PATH }} -C vscode
          echo "UNPACKED_PATH=${{ github.workspace }}/vscode/VSCode-linux-x64" >> $GITHUB_ENV

      - name: Inspect directory
        run: |
          echo "Inspecting unpacked directory..."
          ls -R vscode

      - name: Save paths
        id: save-paths
        run: |
          echo "::set-output name=packaged_path::${{ env.PACKAGED_PATH }}"
          echo "::set-output name=unpacked_path::${{ github.workspace }}/vscode/VSCode-linux-x64"

  create-appimage:
    name: Generate AppImage
    runs-on: ubuntu-latest
    needs: download-and-unpack
    outputs:
      appimage_path: ${{ steps.build.outputs.appimage_path }}
    steps:
      - name: Install dependencies
        run: pip install --upgrade certifi

      - name: Download AppImage creator script
        id: download-script
        run: |
          wget -O createAppImage.py "https://raw.githubusercontent.com/Emiliopg91/AppImage-Creator/main/createAppImage.py"

      - name: Build AppImage
        id: build
        run: |
          version=$(cat ${{ needs.download-and-unpack.outputs.unpacked_path }}/resources/app/package.json | jq -r .version)
          python3 createAppImage.py \
            --entrypoint=${{ needs.download-and-unpack.outputs.unpacked_path }}/code \
            --name="Visual Studio Code" \
            --version=$version \
            --icon=${{ needs.download-and-unpack.outputs.unpacked_path }}/resources/app/resources/linux/code.png \
            --description="Code Editing. Redefined." \
            --desktop="./vsc.desktop"
          echo "::set-output name=appimage_path::${{ github.workspace }}/Visual_Studio_Code-$version.AppImage"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: create-appimage
    steps:
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Visual Studio Code"
          automatic_release_tag: latest
          prerelease: false
          files: |
            ${{ needs.download-and-unpack.outputs.packaged_path }}
            ${{ needs.create-appimage.outputs.appimage_path }}
            ${{ needs.create-appimage.outputs.appimage_path }}.zsync
          repo_token: ${{ secrets.GITHUB_TOKEN }}
