name: Package & release VSCode AppImage

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta a las 12:00 AM UTC cada día
  workflow_dispatch:     # Permite la ejecución manual del workflow

permissions:
  contents: write  # Permitir escritura en el repositorio (incluyendo tags)

jobs:
  download-and-unpack:
    name: Download and Unpack VSCode
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libfuse2

      - name: Download latest VSCode
        run: |
          wget -O vscode.tar.gz "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
          mkdir vscode
          tar -xzvf vscode.tar.gz -C vscode

      - name: Save paths
        id: unpacked
        run: | 
          echo "PACKAGED_PATH=${{ github.workspace }}/vscode.tar.gz" >> $GITHUB_ENV
          echo "UNPACKED_PATH=${{ github.workspace }}/vscode/VSCode-linux-x64" >> $GITHUB_ENV

  create-appimage:
    name: Generate AppImage
    runs-on: ubuntu-latest
    needs: download-and-unpack
    steps:
      - name: Install dependencies
        run: pip install --upgrade certifi

      - name: Download AppImage creator script
        run: |
          wget -O createAppImage.py "https://raw.githubusercontent.com/Emiliopg91/AppImage-Creator/main/createAppImage.py"

      - name: Build AppImage
        run: |
          version=$(cat ${{ env.UNPACKED_PATH }}/resources/app/package.json | jq -r .version)
          python3 createAppImage.py \
            --entrypoint=${{ env.UNPACKED_PATH }}/code \
            --name="Visual Studio Code" \
            --version=$version \
            --icon=${{ env.UNPACKED_PATH }}/resources/app/resources/linux/code.png \
            --description="Code Editing. Redefined." \
            --desktop="./vsc.desktop"
          echo "APPIMAGE_PATH=Visual_Studio_Code-$version.AppImage" >> $GITHUB_ENV

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: create-appimage
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Visual Studio Code ${{ env.APP_VERSION }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            ${{ env.PACKAGED_PATH }}
            ${{ env.APPIMAGE_PATH }}
            ${{ env.APPIMAGE_PATH }}.zsync
          repo_token: ${{ secrets.GITHUB_TOKEN }}
