name: Package & release VSCode AppImage

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta a las 12:00 AM UTC cada día
  workflow_dispatch:     # Permite la ejecución manual del workflow

permissions:
  contents: write  # Permitir escritura en el repositorio (incluyendo tags)

jobs:
  download-binary-app:
    name: Download app binaries
    runs-on: ubuntu-latest
    steps:
      - name: Download latest VSCode
        run: |
          wget -O vscode.tar.gz "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
      
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-binary
          path: vscode.tar.gz

  generate-appimage:
    name: Generate AppImage
    runs-on: ubuntu-latest
    needs: download-binary-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libfuse2
          pip install --upgrade certifi
          wget -O createAppImage.py "https://raw.githubusercontent.com/Emiliopg91/AppImage-Creator/main/createAppImage.py"

      - name: Download binaries from previous job
        uses: actions/download-artifact@v4
        with:
          name: vscode-binary
          path: .

      - name: Unpack binaries
        run: |
          tar -xzvf ./vscode.tar.gz

      - name: Generate AppImage
        run: |
          version=$(cat ./VSCode-linux-x64/resources/app/package.json | jq -r .version)
          python3 ./createAppImage.py \
            --entrypoint=./VSCode-linux-x64/code \
            --name="Visual Studio Code" \
            --version=$version \
            --icon=./VSCode-linux-x64/resources/app/resources/linux/code.png \
            --description="Code Editing. Redefined." \
            --desktop="./vsc.desktop"
        
      - name: Upload AppImage and zsync files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage-files
          path: |
            ${{ env.APPIMAGE_PATH }}
            ${{ env.APPIMAGE_PATH }}.zsync

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: generate-appimage
    steps:
      - name: Download tar.gz, AppImage, and AppImage.zsync
        uses: actions/download-artifact@v4
        with:
          name: vscode-binary
          path: .
          
      - name: Download AppImage and zsync files
        uses: actions/download-artifact@v4
        with:
          name: appimage-files
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Visual Studio Code ${{ steps.generate-appimage.outputs.version }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            ./*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
