name: Package & release AppImage

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta a las 12:00 AM UTC cada día
  workflow_dispatch:     # Permite la ejecución manual del workflow  
  push:
    branches:
      - main

permissions:
  contents: write  # Permitir escritura en el repositorio (incluyendo tags)

jobs:
  generate-appimage:
    name: Generate and publish AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download latest binaries
        run: |
          binariesurl=$(cat app.desktop | grep Binaries-Url)
          IFS="=" read -r name url <<< "$binariesurl"
          wget -q -O binaries.tar.gz $url

      - name: Unpack binaries
        run: |
          tar -xzf ./binaries.tar.gz

      - name: Generate AppImage
        id: generate-appimage-file
        uses: Emiliopg91/AppImage-Creator@latest      

      - name: Rename binaries
        run: mv binaries.tar.gz binaries-${{ env.APP_VERSION }}.tar.gz

      - name: Create GitHub Release
        id: create_release
        if: env.IS_UPDATE == 'true'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ env.APP_VERSION }}
          automatic_release_tag: ${{ env.APP_VERSION }}
          prerelease: false
          files: |
            binaries-${{ env.APP_VERSION }}.tar.gz
            ${{ env.APPIMAGE_PATH }}
            ${{ env.APPIMAGE_PATH }}.zsync
            
          repo_token: ${{ secrets.GITHUB_TOKEN }}
